### ISSUE TITLE
ch00: Preface

### ISSUE THREAD

**Issue by chai2010** [golang-china/gopl-zh#1]
gitbook 可以同时保留 中英文.

**Comment by cch123** [comment]
这个英文原文贴上来是不是有。。风险

**Comment by chai2010** [comment]
@cch123 确实会有风险. 还是只保留中文吧.

**Comment by chai2010** [comment]
https://github.com/golang-china/gopl-zh/commit/8c4fb050baf1511caed9f48df6cdef4406c8c964 初译序言开头部分.

**Comment by chai2010** [comment]
done
