### ISSUE TITLE
什么时候能好呢？

### ISSUE THREAD

**Issue by lhyhsx** [golang-china/gopl-zh#1]
非常非常的感谢你们的翻译。
近段时间正在看这本书，今天突然就不能看了。请问什么时候可以恢复呢？

**Comment by Centimitr** [comment]
已发邮箱，另外https://github.com/search?utf8=%E2%9C%93&q=gopl有原版。

**Comment by chai2010** [comment]
很可能以后无法公开，只能私下分享了。年后会沟通下，有结果会在这里说的

**Comment by weaming** [comment]
@chai2010 谢谢

**Comment by chai2010** [comment]
暂时在 QQ群(531508541) 交流

**Comment by weaming** [comment]
镜像：http://docs.ruanjiadeng.com/gopl-zh/

**Comment by chai2010** [comment]
https://github.com/yidao620c/python3-cookbook/issues/83

**Comment by Akagi201** [comment]
去TMD DMCA, 搞起, 不行就像草榴一样, 各种镜像, 看他们怎么封.

**Comment by weaming** [comment]
@Akagi201 这都能碰到你？哈哈哈

**Comment by Akagi201** [comment]
@weaming 哈哈, I am everywhere. PS: 最近假期打算看完这本书.

**Comment by sakds** [comment]
镜像：https://docs.hacknode.org/gopl-zh/ 
每天自动检查并构建最新版本。

**Comment by gqdw** [comment]
qq群好像搜不到。531508541
