### ISSUE TITLE
有翻译授权？

### ISSUE THREAD

**Issue by iyee** [golang-china/gopl-zh#125]
印象里已经有国内出版社买了版权。

**Comment by chai2010** [comment]
请认准标题: **Go圣经中文读书笔记(你懂的)**.

我们买了正版的英文版, 这是我们的学习笔记(你懂的).

**Comment by iyee** [comment]
哈，我是不介意啦，原版我也买了的。。

**Comment by cloudzhou** [comment]
我觉得这么出版是不合适的

**Comment by chai2010** [comment]
@cloudzhou 目的不是为了出版, 放github只是方便学习交流, 等读完之后(或D&K抗议的话), 会重新想下怎么处理这些学习笔记.

**Comment by v2e4lisp** [comment]
我觉得这样发布出来是不对的。应该要经过原作者或者是拥有这本书版权的相关机构的认可，才可以发布。刚查看了一下原书，上面有写版权方面的问题和 Pearson Education, Inc. 联系。

**Comment by cloudzhou** [comment]
其实这个 repo 的作者完全知道这是违法的，只是不在乎而已。
算了，这就是国内现实的版权意识，后续的出版社要哭了...
我记得以前我需要 copy 一段代码时，还特别写信咨询了作者。


发自 网易邮箱大师
在2015年12月01日 19:12，Yan Wenjun 写道:

我觉得这样发布出来是不对的。应该要经过原作者或者是拥有这本书版权的相关机构的认可，才可以发布。刚查看了一下原书，上面有写版权方面的问题和 Pearson Education, Inc. 联系。

**Comment by chai2010** [comment]
@cloudzhou 我真没觉得是多大的事情.
英文的盗版pdf出了, 对英文的销售会有多大的影响呢?
买正版的人还是会买正版.

我以前的一个博文还被人直接复制/粘贴出版到书里了,
我也只是在网上提了下而已(按照版权者的建议是该起诉吗).

如果真的把版权看得太重.
那么 Linux, Android 都有侵权的嫌疑(UNIX的API凭什么没有版权?).
国内的第一版<算法导论>凭什么出版?
还有很多自主创新点东西....

我不相信有哪位没有用过盗版软件, 没有看过盗版书, 没有看过盗版电影的(比尔盖茨也不例外).
大家都是有原罪的, 不要总把自己看的那么纯洁/清高.

对我来说, 版权不是多大的事情.
我会尽量尊重版权, 但是也不会会了这个放弃很多.

**Comment by chai2010** [comment]
重新打开这个 Issue, 随便吐槽.

**Comment by rfyiamcool** [comment]
版权还是重要的

**Comment by GeekerSlz** [comment]
我觉得吧,以学习研究,分享,为目的,然后发布出来都没什么.
但如果你把这个东西整理完了,拿出来商业化,卖钱或者谋取其他利益,就需要斟酌了.
像VS2015,IntelliJ idea不都分商业版和交流版的么.

**Comment by cloudzhou** [comment]
@chai2010 我记得 API 确实是没有版权的。
大家是有原罪，但是并不是可以以此合理化。
关于盗版的，以前的 MP3 几乎毁了国内的原创音乐。日本外语书籍翻译业及其发达，因为出版业人员活得不错。我的同事大半年翻译一本书，稿费2，3千，很多人做翻译无非为了知名度和兴趣，收益真是得不偿失。所以你看到国内翻译的书籍质量非常差。
回到这个问题，你想想，如果一个人辛辛苦苦翻译大半年，一出版发现外面盗版都发行 N 久了，内心不知道要怎么想。
这是一个劣币驱动良币的过程。最后就是大家都不认真翻译，不认真写书了。

**Comment by chai2010** [comment]
@cloudzhou API 还没有绝对的定论. 不然 Java 的官司为何拖了这么久.
说到底还是因为, 如果 API 有版权, 会导致整个IT或整个产业承受的代价太重而已.

关于音乐或图书, 如果是在大家能接受的价格内, 我还是倾向与购买正版的.
(比如水果的Music订阅, 虽然我还没有用, 但是我会花钱订阅.)

回到技术图书翻译这个问题. 真的不能完全怪大家忽视版权.
主要原因是出版社出的烂书/烂的翻译太多, 很多就是承包给底下学生翻译(甚至不是对应的用户), 而且跟进速度非常之慢.
具体到gopl, 日本就是首发(这和他们国家对整个科技文献的态度是有关系的).
如果一切依赖出版社的翻译速度来学习了解新的技术, 那真的啥也不用干了.

真正劣币驱良币的是那些只认短期利益的纯商业行为吧.

回到我个人, 我觉得个人完全是有翻译的权利的.
没有的只是出版和发布的权利而已.
但是, 什么样的行为算是发布呢?

我可以说, github 只是我临时存放的空间.
我没有授权给别人看我个人私下的翻译, 你们如果非要看, 那不是我的责任.
如果 github 觉得这个可能是会导致侵权的发布行为, 我可以另换其他私有的 git 仓库.
说到底, 这个是我的个人学习行为(我并不想别人看或传播, 非商业行为, 我也不想赚钱).

翻译这个事情不应该是只有出版社花钱就说了算的.

开源环境的就是优胜劣汰, 我喜欢这个规则.

**Comment by lszhu** [comment]
只要原作者不抗议，译者不以此牟利，无妨。

**Comment by flike** [comment]
为大家做贡献，支持！

**Comment by hoperuin** [comment]
支持chai大,赞！

**Comment by chai2010** [comment]
补充一点. 这是我们的读书笔记和英文翻译练习, 非商业行为, 保留我们的版权.
严禁任何商业行为使用或引用该 读书笔记 的全部或部分内容!
