### ISSUE TITLE
发现两个翻译小问题

### ISSUE THREAD

**Issue by lszhu** [golang-china/gopl-zh#132]
2.1节最后一个单词抄错了，应为：escapeHtml
2.3.4最后一句翻译欠妥
原文： For example, keeping unnecessary pointers to short-lived objects within long-lived objects, especially global variables, will prevent the garbage collector from reclaiming the short-lived objects. 
应翻译为：
比如，将指向短生命周期对象的指针保存到具有长生命周期的对象中，特别是全局变量时，会阻止对短生命周期对象的垃圾回收。

**Comment by chai2010** [comment]
感谢你的建议. 源文件已经修改了, html 还没有更新.

如果没有其他问题, 那么在 html 更新后 会关闭这个 issue.

**Comment by chai2010** [comment]
https://github.com/golang-china/gopl-zh/commit/4851caf8808de4f398dedd8648034fb687f60692
