### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by wangxiyu191** [golang-china/gopl-zh#133]
gopl-zh/ch0/ch0-03.md
第一行 ython是不是python漏了一个p

**Comment by wangxiyu191** [comment]
第一行 ython是不是python漏了一个p

**Comment by wangxiyu191** [comment]
另外并不是特别认同你们这种翻译方式。。

**Comment by chai2010** [comment]
@wangxiyu191 感谢反馈. 这种学习方式我也不喜欢, 如果首发能包含中文版就完美了.

**Comment by chai2010** [comment]
https://github.com/golang-china/gopl-zh/pull/138
