### ISSUE TITLE
第13章 低级编程

### ISSUE THREAD

**Issue by wwek** [golang-china/gopl-zh#135]
第13章 低级编程 是否翻译为 第13章 底层编程 更好

**Comment by chai2010** [comment]
开始用的是 底层编程, 我对这2个也是比较困扰.
暂时保留这个问题, 等其他内容完善了再深入讨论吧.

**Comment by achun** [comment]
有时候我们可能会放弃部分语言特性而优先选择更好的性能优化, 与其他语言编写的库胡操作, 或者不用纯Go语言来实现某些函数.

"胡操作" 这词怎么这么别扭啊

**Comment by chai2010** [comment]
@achun 互操作. 有很多类似的问题, 后面得慢慢校对了.
