### ISSUE TITLE
ch10-07中gitbook格式错误及修复

### ISSUE THREAD

**Issue by lszhu** [golang-china/gopl-zh#153]
本地使用gitbook输出时有以下错误：
Template render error: (G:\etc\book\gopl-zh\ch10\ch10-07.md)
  Template render error: (G:\etc\book\gopl-zh\ch10\ch10-07-6.md) [Line 77, Column 26]
  expected variable end (In file 'ch10/ch10-07.md')
分析ch10-07-6.md发现，77、84、90、101四行文本不符合gitbook的格式，请参考：
http://help.gitbook.com/format/templating.html
的Escaping段说明，需将上面四行中的双花括号部分加以处理（抑制转义），比如按以下方式分别修改上述4行：
$ go list -f '{% raw %}{{join .Deps " "}}{% endraw %}' strconv
$ go list -f "{% raw %}{{join .Deps \" \"}}{% endraw %}" strconv
$ go list -f '{% raw %}{{.ImportPath}} -> {{join .Imports " "}}{% endraw %}' compress/...
$ go list -f "{% raw %}{{.ImportPath}} -> {{join .Imports \" \"}}{% endraw %}" compress/...

**Comment by chai2010** [comment]
@lszhu 暂时没有GitBook 环境, 等明天再看看. 非常感谢.
