### ISSUE TITLE
README 移除书的封面

### ISSUE THREAD

**Issue by Unknwon** [golang-china/gopl-zh#154]
如果以读书笔记为侧重点并且不提供任何盗版文件，应该是打了版权的擦边球。

但使用官方未授权的 PDF 封面会有假借正版名义进行宣传的嫌疑，建议移除，保留 URL 即可。

顺便支持柴大 :trollface:

**Comment by chai2010** [comment]
@Unknwon 恩, 应该自己弄一个封面.

**Comment by chai2010** [comment]
done
