### ISSUE TITLE
怎么突然就繁体了。

### ISSUE THREAD

**Issue by CodyGuo** [golang-china/gopl-zh#157]
怎么突然就繁体了。

**Comment by chai2010** [comment]
有购买了简体出版权的出版社说这个项目侵权. 为了避嫌, 转繁体.
如果你喜欢简体, 自己输入 `make w2zh` 转下.

**Comment by CodyGuo** [comment]
好的，谢谢。繁体看不习惯。

**Comment by chai2010** [comment]
该项目有可能关闭(希望不会), 建议自己做好相关准备

**Comment by CodyGuo** [comment]
这么好的项目，千万不要关闭。辛苦了。。。继续努力。

**Comment by lszhu** [comment]
由原来的简体转成繁体时，太多的繁体字转换错了。主要问题应该是，简化字在不同词语中会对应多个繁体字。比如“发”，表示发达和头发时，对应不同的繁体字，而文中全转换为头发的髮。
简体转繁体的程序要分析的琐碎问题非常多，建议通过微软office word的简转繁功能，实现简体到繁体的转换。

**Comment by chai2010** [comment]
@lszhu 转繁体字只是为了规避出版社的简体版权的风险. 内容还是简体的, 繁体只是作为一种中间编码的方式. 大家最好在自己的电脑上转回简体阅读.
