### ISSUE TITLE
ch01-2: Command-Line Arguments

### ISSUE THREAD

**Issue by chai2010** [golang-china/gopl-zh#17]
#3

**Comment by cch123** [comment]
done

**Comment by chai2010** [comment]
https://github.com/golang-china/gopl-zh/commit/2032c8dea8b8ba9d6091b8bd4e6770e1373cff48

**Comment by chai2010** [comment]
https://github.com/golang-china/gopl-zh/commit/a86990e1f8e941afded9e3859ce35192a43e3ef3
