### ISSUE TITLE
在Go1.6之前完成翻译

### ISSUE THREAD

**Issue by chai2010** [golang-china/gopl-zh#173]
Go1.6大约在2月1日后发布。希望我们能在1月20号前能完成翻译（剩下的时间做校验）。
估计每周需要完成1～2节内容的翻译。

如果感觉时间比较紧，每个人可以将自己章节中剥离一节让别人帮忙翻译。
如果1周内没有任何进展的话，我会直接剥离部分章节让别人翻译。

- ~~第5章(#8)：~~@CrazySssst
- ~~第7章(#2)：~~@foreversmart
- ~~第8章(#10)：~~@cch123
- ~~第9章(#11)：~~@cch123
- ~~第12章(#14)：~~ @chai2010

**Comment by CodyGuo** [comment]
加油！ 在windows下没有编译通过

**Comment by chai2010** [comment]
ch12 done

**Comment by chai2010** [comment]
ch8-4(#82) 转给 @chai2010

**Comment by chai2010** [comment]
ch8 done

**Comment by chai2010** [comment]
大家如果发现英文原版有错误的话，直接去 [gopl](https://github.com/adonovan/gopl.io/) 项目提交[issue](https://github.com/adonovan/gopl.io/issues)。

**Comment by chai2010** [comment]
ch5 done

**Comment by chaobj001** [comment]
超赞

**Comment by chai2010** [comment]
Go1.6Beta2已经出来好几天了。
大家得抓紧了。

@foreversmart @cch123

**Comment by foreversmart** [comment]
预计明天晚上可以全部完成

**Comment by chai2010** [comment]
@foreversmart +10086

**Comment by cch123** [comment]
done了

**Comment by foreversmart** [comment]
ch7 done

**Comment by chai2010** [comment]
@foreversmart 给力。

大家先将自己翻译的章节粗校下，别人翻译的章节也可以随便校对。
粗校完成后，就可以正式发布了。
