### ISSUE TITLE
ch07: Interfaces

### ISSUE THREAD

**Issue by foreversmart** [golang-china/gopl-zh#2]

**Comment by chai2010** [comment]
Good. 是接口吧.

**Comment by foreversmart** [comment]
是的，这样可以在强化下那一章的知识

**Comment by chai2010** [comment]
@foreversmart 是否还在翻译, 如果没有的话, 我打算翻译了.

**Comment by foreversmart** [comment]
在翻译，最近有点忙。晚上提交下最近的翻译，上次简体和繁体转换格式乱点了。

**Comment by foreversmart** [comment]
在翻译，最近有点忙。晚上提交下最近的翻译，上次简体和繁体转换格式乱点了。

**Comment by chai2010** [comment]
@foreversmart 理解了。我最近在review已经翻译的部分，你可以上传已经翻译的部分，格式和标点在review阶段再处理。

PS: 前端时间担心出版社版权问题，强制清除了之前的log（简体部分），以前git克隆的版本可能不好用了。

**Comment by foreversmart** [comment]
嗯，好的

**Comment by foreversmart** [comment]
基本完成了
