### ISSUE TITLE
gitbook 生成的 html 文档在手机 Chrome 等浏览器上不现实最上角图标按钮。

### ISSUE THREAD

**Issue by iamybj** [golang-china/gopl-zh#20]
gitbook 生成的 html 文档在手机 Chrome 等浏览器上不现实最上角图标按钮。但是火狐浏览器可以显示。
尤其是无法显示侧边目录栏，不方便阅读。

**Comment by cch123** [comment]
这个感觉是gitbook的兼容性问题啊。。
不太晓得该怎么修复orz
