### ISSUE TITLE
一个拼写错误

### ISSUE THREAD

**Issue by lszhu** [golang-china/gopl-zh#204]
5.4节第一行
string.Contains的string应为strings

**Comment by cch123** [comment]
我觉得直接提pr就成了orz

**Comment by lszhu** [comment]
我发现，还有其它地方，比如5.5节，string.Map，其中string也应是strings。
建议整体查找替换一下

**Comment by chai2010** [comment]
tools目录下的脚本可以查：`go run ./tools/lsdir.go . "\.md$" "string\."`

好像还有一些:

```
_book\ch3\ch3-05-4.md
ch1\ch1-02.md
ch1\ch1-03.md
ch12\ch12-02.md
ch3\ch3-05-4.md
total 5
```
