### ISSUE TITLE
是否需要增加一章用于较长的扩展内容？

### ISSUE THREAD

**Issue by chai2010** [golang-china/gopl-zh#215]
在gopl中，并不包含全部的Go语言特性介绍，比如下面这些：

- 面向对象：Go的组合和C++的继承有何区别？
- 接口部分：匿名接口的嵌入、内部接口的导出
- cgo部分：C内存的辅助管理
- 工具：go generate

还有一些比较重要的库（官方维护的），比如grpc等。

可能用小短文的方式单独放一章比较好。

因为版权问题，该部分最好自己写。

**Comment by prife** [comment]
这本是译著，译者可能需要克制自己再创作的欲望:-)，正式出版的话，作为正文一章不妥。如果这些内容比较重要，是不是可以在译者序/跋里提及，提供网络版本供读者阅读下载？

**Comment by chai2010** [comment]
恩，应该保持gopl的独立性，作为额外补充文档更好一点。

**Comment by cch123** [comment]
感觉应该是chai大的一篇博文什么的。。。
放gopl确实不合适
