### ISSUE TITLE
关于书名“go语言圣经”

### ISSUE THREAD

**Issue by prife** [golang-china/gopl-zh#217]
`The C programming language`国内译为《C程序设计语言》，见 [http://book.douban.com/subject/1139336/] ，`The C programming language`译为《C++程序设计语言》，见 [http://book.douban.com/subject/4604591/]
ch1-01里的`The C programming language`也译为《C語言聖經》了。

为何没有遵守这个惯例呢？

**Comment by cch123** [comment]
这件事情。。。
我觉得你可以翻翻issue想一想。。

**Comment by prife** [comment]
你是想说版权问题？都已经当学习笔记发上来了，还担心这个吗？

**Comment by chai2010** [comment]
以上其实只是机械工业出版社的惯例，Java那本就直译为《Java编程语言》：http://product.china-pub.com/15495

我个人感觉叫《x程序设计语言》纯粹是凑字数，本质内容就是《x语音》或《X编程语言》，其实主要是觉得叫《go程序设计语言》不够霸气。

机械工业出版社就是用你说的那个名字（它们号称买了大陆的专有版权，要求马上删除侵权内容，还好我们这个是从英文原版来的学习笔记，和它们没有任何关系；当然如果d&k本人有异议的话，肯定会考尊重他们的意见）。

**Comment by prife** [comment]
原来是这个原因，带有“圣经”我还以为是台版译名。坦白说机械工业出版社翻译的C/C++两本质量不错，译者一个是徐波，一个是裘宗燕。命名为“XX程序设计语言”是否有凑字数的嫌疑，这个见仁见智了。既然书名国内存在版权争议，那也只好这样了。但是ch1-01.md我以为还是改用国内正式出版的名称较妥。

**Comment by chai2010** [comment]
ch1-01.md的内容：

> 我们以1978年出版的C语言圣经《The C Programming Language》中经典的“hello world”案例来开始吧（译注：本书作者之一Brian W. Kernighan也是C语言圣经一书的作者）。C语言对Go语言的设计产生了很多影响。

这里并没有提到中文版的名字，“C语言圣经”只是一个修饰。而且，我们的译文属于Go语音和英文翻译的学习笔记，完全是在gopl学习过程而完成的；C语言圣经的信息，也是参考的英文版本，本译文和机械工业出版社是没用任何关系的（也不关心它们是否真的出版过）。

ps：它们是否有大陆专有版权，本人并不关心，也没心思去侵它们的权。但是，我完全尊重k&r和d&k本人的意见，因为我是用他们原版的英文教材学习的。

**Comment by chai2010** [comment]
文中对c那本引用的链接都是英文原版的地址：
http://s3-us-west-2.amazonaws.com/belllabs-microsite-dritchie/cbook/index.html

**Comment by prife** [comment]
原来如此。既然有这些考虑，ch1-01.md里是不是直接保留原文更好呢？ 
@chai2010 意下如何？

**Comment by chai2010** [comment]
直接保留原文具体是什么意思呢？

ps：同样时版权考虑，文中尽量避免直接出现英文原文拷贝（那就真的时侵权了），但是自己重新生成的中文就不同了。

**Comment by prife** [comment]
毕竟这本书已经出版了，大家都知道它在国内叫《C程序设计语言》，正文里放上另外的名字，会让不明真相的围观群众疑惑（比如我），毕竟你的这些考虑读者并不知道；其次，保留原文读者自然明白，况且引用只是个正式出版的书名，我觉得并不能算侵权。想想念书时写的论文引用了那么多也都是直接写的。就算真有版权有些许问题，两权相害取其轻（我觉得对读者造成的困扰的问题更大）。

**Comment by chai2010** [comment]
毕业论文可是要出版的，侵权、抄袭、错误都是大问题。而这个译文本质上就是一个学习笔记，也尽量和国内的出版的中文划清关系。说到底这是一个个人学习行为（避免侵权的风险），矛盾地说我是反对大家到处传播的，我想读者应该能够体谅这其中的意思。如果真是觉得影响阅读的话，我强烈建议买个英文原版和2017年可能会出版的中文版对照来读。

**Comment by prife** [comment]
好吧，我尊重你的选择，但保留个人意见。正在校对ch1-01.md，稍后发上来，那儿的处理保留你原来译文。

**Comment by chai2010** [comment]
Go语言圣经 这个名字大家会慢慢适应的，等适应后《x程序设计语言》看起来就会很别扭了。
从Go语音简洁的编程哲学角度说，我也绝得《go编程语言》要比《go程序设计语言》要好得多，这个可以从Go、func、fmt、defer这些简洁的名字中对比。

**Comment by chai2010** [comment]
@prife 感谢你的校对工作

**Comment by prife** [comment]
翻译其实也是个编译器的活，我们作为“编译器”，第一点就是保证正确性，随后才考虑其他。翻译讲究信、达、雅。加上圣经二字我觉得显然破坏了“正确性”，在保证正确性的基础上，既要雅、也要考虑行业惯例。哎，说到底都是个trade-off的工作。

**Comment by chai2010** [comment]
我比较同意“正确性”的原则，不可否认，我们夹了一些私货。
翻译过程本身确实是在验证我们之前对Go语音的理解，已经发现了一些作为“翻译编译器”的我们和gopl的bug。
所以说，关于gopl中翻译的正确性我们是第一看重的，但很多地方不是直译。

ps：说到行业惯例，国内很多地方说到c语音之父可能是指谭老师。因此，我们一般避免引用国内的惯例和网站。
