### ISSUE TITLE
有计划提供 pdf 版本吗？

### ISSUE THREAD

**Issue by GameXG** [golang-china/gopl-zh#221]

**Comment by chai2010** [comment]
gitbook可以生成pdf，不过生成的pdf排版很难看（特别是目录部分）。
目前还不知道如何改进生成的pdf。

**Comment by GameXG** [comment]
主要是字体的问题，之前本地生成时指定为微软雅黑字体能达到比较好的效果。不过不清楚 gitbook 有没有中文的字体。

{
    "pluginsConfig": {
        "fontSettings": {
            "theme": "white", 
            "family": "msyh", 
            "size": 2
        }
    }, 
    "pdf": {
        "pageNumbers": true, 
        "fontSize": 18, 
        "paperSize": "a4", 
        "margin": {
            "right": 30, 
            "left": 30, 
            "top": 30, 
            "bottom": 30
        }, 
        "headerTemplate": null, 
        "footerTemplate": null
    }
}



也可以通过 travis 自动生成 pdf ，另外几个中文书籍的例子：
https://github.com/billryan/programming-notes/blob/master/.travis.yml
https://github.com/billryan/algorithm-exercise/blob/master/.travis.yml

**Comment by chai2010** [comment]
因为存在版权风险，不会提供pdf，大家自己整吧。
