### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by victor-simida** [golang-china/gopl-zh#26]
302页，“多少服务端 C 和 C 艹程序员为此尽折腰”

应改为“多少服务端 C 和 C++程序员为此竟折腰”

**Comment by cch123** [comment]
orz，这其实是一种幽默来的

**Comment by dreamrover** [comment]
不是“竟”吧，应该是竞相的“竞”。

**Comment by cch123** [comment]
@dreamrover ，确实。。感觉语文都还给老师了
