### ISSUE TITLE
关于 2.7 节第三段词法块部分的翻译修正

### ISSUE THREAD

**Issue by lovdin** [golang-china/gopl-zh#27]
**2.7 作用域 第三段**

**[现有译文]:**

> 我们可以这样理解,语法块可以包含其他类似组批量声明等没有用花括弧包含的代码,我们称之为语法块。

**[英文原文]:**

> We can generalize this notion of blocks to include other groupings of declarations that are not explicitly surrounded by braces in the source code; we’ll call them all lexical blocks.

现有翻译不太通顺，而且概念上也不对（是词法块不是语法块），英文的意思大概是这样吧：

> 我们可以把块（block）的概念推广到包括其他声明的组群（群组），这些声明在代码中并未显式地使用花括号包裹起来，我们称之为**词法块**。

**Comment by cch123** [comment]
@lovdin ，感谢反馈，估且是改了，不过总感觉有些别扭orz
