### ISSUE TITLE
1.6 Fetching URLs Concurrently

### ISSUE THREAD

**Issue by ryanfakir** [golang-china/gopl-zh#29]
练习1.10的之前的最后一句话， 有点问题
原文： Having main do all the printing ensures that output from
each goroutine is processed as a unit, with no danger of interleaving if two goroutines finish at the
same time.
翻译： 通过在main函数使用channel 阻塞接受各个goroutine的输出，可以保证每个goroutine下的输出是有序单位，而不用担心当两个goroutines同时而导致的交错选择问题。

ps：练习1.11没有翻译

**Comment by cch123** [comment]
看起来是老版本的问题，1.11现在应该是有的
