### ISSUE TITLE
[error report] 第七章第五节 示例错误，可能与go版本有关

### ISSUE THREAD

**Issue by zuoRambo** [golang-china/gopl-zh#3]
``` bash
$ go version
go version go1.5.1 darwin/amd64
```

测试代码如下

``` go
package main

import (
    "bytes"
    "io"
)

const debug = true

func main() {
    var buf *bytes.Buffer
    if debug {
        buf = new(bytes.Buffer)
    }
    f(buf)
}

func f(out io.Writer) {
    if out != nil {
        out.Write([]byte("done!\n"))
    }
}

```

按照[7.5.1. 警告：一个包含nil指针的接口不是nil接口](https://docs.ruanjiadeng.com/gopl-zh/ch7/ch7-05.html)，代码应该有panic `panic: nil pointer dereference`但是运行结果显示并没有panic

文中`当main函数调用函数f时，它给f函数的out参数赋了一个*bytes.Buffer的空指针，所以out的动态值是nil。然而，它的动态类型是*bytes.Buffer，意思就是out变量是一个包含空指针值的非空接口（如图7.5），所以防御性检查out!=nil的结果依然是true。`out的动态值为什么是nil呢？不应该是`一个指向新分配的缓冲区的指针`吗？

**Comment by chai2010** [comment]
ch7.5.1 的译文是没有问题的：

> 我们可能会预计当把变量debug设置为false时可以禁止对输出的收集，但是实际上在out.Write方法调用时程序发生了panic：
> 
> ```
> if out != nil {
>    out.Write([]byte("done!\n")) // panic: nil pointer dereference
> }
> ```

当debug打开的时候是正常的，但是当debug被关闭的时候就panic了。

原因是当debug为false的时候，`var buf *bytes.Buffer`是`nil`指针，
但是在转为`out io.Writer`的时候，并不是一个`nil`接口，而是一个`*bytes.Buffer`类型的`nil`对象。

这是`nil`接口的定义导致的：只有type和value都为空时才是nil **接口** (注意：不是`nil` **指针**)。

**Comment by zuoRambo** [comment]
嗯 自己阅读了下 确实是自己看错了
