### ISSUE TITLE
gopl-zh ch6问题反馈

### ISSUE THREAD

**Issue by SilenMark** [golang-china/gopl-zh#31]
# ch6-02  
原著中 的 named type 应该是 用 type 命名过的类型，是与内建类型相对而言的，翻译有些歧义，感觉按中文表达应该是类似于 ‘自定义类型’ 或者 ‘命名类型’ 这种意思  。
[stackoverflow上的解释](http://stackoverflow.com/questions/32983546/named-and-unnamed-types)

**Comment by cch123** [comment]
@SilenMark ，具体是哪段有问题呢orz，我grep了一下这一章应该也有译作命名类型的

**Comment by cch123** [comment]
@SilenMark ，抽时间翻了一下，原来是说最后一段，已经把命名类型补上了~
