### ISSUE TITLE
个人认为标题呀，不要翻译成xx圣经，有点恶心。

### ISSUE THREAD

**Issue by ilaziness** [golang-china/gopl-zh#34]
感觉有点宗教意味。本身有些狂热GO粉就被人说成是宗教分子，还取这样的标题。取个正常点的名字不是挺好吗？

**Comment by cch123** [comment]
@ddyllen-z ，大家都是码农，可以心态放轻松些~
比如别人随口一说php是最好的语言，你真要去较真么orz
