### ISSUE TITLE
gopl-zh 8.4.2 问题反馈

### ISSUE THREAD

**Issue by jingxize** [golang-china/gopl-zh#35]
在gopl.io/ch8/pipeline2这个代码实例下边的文字说明当中，”对于每个打开的文件，都需要在不使用的使用调用对应的Close方法来关闭文件。”，想要表达的应该是“都需要在不使用的_时候_调用”

**Comment by jingxize** [comment]
修改issues标题

**Comment by jingxize** [comment]
修改标题

**Comment by cch123** [comment]
@jingxize ，你看的也是老版本
这些已经修正过了
