### ISSUE TITLE
CH12.8 显示一个类型的方法集

### ISSUE THREAD

**Issue by chenchuangchn** [golang-china/gopl-zh#36]
1.  每次v.Method(i)方法调用都返回一个reflect.Value以表示对应的值（§6.4），也就是一个方法是帮到它的接收者的。——也就是一个方法是帮到它的接收者。什么意思，感觉这段话翻译的没看懂，能否加个译注。
2.（我们之类没有演示）——是不是打错字了，是不是 “我们这里没有演示”。

**Comment by cch123** [comment]
fixed
