### ISSUE TITLE
ch7-07可能有一个错字

### ISSUE THREAD

**Issue by is0xb** [golang-china/gopl-zh#39]
发现下面是专用的提交嘛，那我写下面去吧，管理人员关闭这个issues吧

在下面的程序中，我们创建一个ServeMux并且使用它将URL和相应处理/list和/price操作的handler联系起来，这些操作逻辑都已经被分到不同的方法中。然后我门在调用ListenAndServe函数中使用ServeMux为主要的handler。

我的理解应该是我们

**Comment by cch123** [comment]
fixed
