### ISSUE TITLE
建议增加制作好的pdf

### ISSUE THREAD

**Issue by dpc2035** [golang-china/gopl-zh#42]
想要打印成纸质书,得先制作成pdf, 
需要安装node,gitbook
而且, 用gitbook制作pdf时, 会报错:
Cannot find module 'internal/util/types'
...
要解决这个问题,又得用不少时间精力
所以建议增加制作好的pdf,直接下载下来就能看,
今天一上午被这个问题搞得很累,还没解决...

**Comment by chai2010** [comment]
这个项目会删除
