### ISSUE TITLE
cha12.6的一个示例过时了，有bug

### ISSUE THREAD

**Issue by TheStarBoys** [golang-china/gopl-zh#48]
![image](https://user-images.githubusercontent.com/41286328/66307332-bd99f480-e936-11e9-9c22-20dcc7c958fa.png)
如图，红色圈起来的部分，现在的方法有三个返回值
![image](https://user-images.githubusercontent.com/41286328/66307381-e1f5d100-e936-11e9-8cf2-d2d49ce41220.png)

**Comment by cch123** [comment]
欢迎 PR，https://github.com/gopl-zh/gopl-zh.github.com
