### ISSUE TITLE
第七章翻译

### ISSUE THREAD

**Issue by ghost** [golang-china/gopl-zh#53]
第七章翻译是认真的吗？比机翻还糟糕！

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/44697392/76084022-f45d5f00-5fe9-11ea-89a0-c7da1d572c35.png)
![image](https://user-images.githubusercontent.com/44697392/76084035-fd4e3080-5fe9-11ea-8d89-a428422c144d.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/44697392/76084056-09d28900-5fea-11ea-8c24-6d59c2d3e3ba.png)
![image](https://user-images.githubusercontent.com/44697392/76084099-1d7def80-5fea-11ea-8fd0-5ffadbe474cd.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/44697392/76084121-2a024800-5fea-11ea-85db-2dc117c9646b.png)
![image](https://user-images.githubusercontent.com/44697392/76084134-2ec6fc00-5fea-11ea-907f-cf1a317b76ad.png)
![image](https://user-images.githubusercontent.com/44697392/76084145-32f31980-5fea-11ea-8c1e-a46df6b81f39.png)

**Comment by guojiaoniu** [comment]
![image](https://user-images.githubusercontent.com/44697392/76084502-f70c8400-5fea-11ea-9d37-014eb7945947.png)
![image](https://user-images.githubusercontent.com/44697392/76084512-fb38a180-5fea-11ea-8600-7b648c9b61b5.png)

**Comment by cch123** [comment]
网友翻译，要求不能太高，如果有不通顺的，欢迎来提 PR，https://github.com/gopl-zh/gopl-zh.github.com
