### ISSUE TITLE
ch8.10 ex8.12 翻译存在歧义

### ISSUE THREAD

**Issue by caffiene0079** [golang-china/gopl-zh#58]
原文：Make the broadcaster announce the current set of clients to each new arrival.
现翻译成：使broadcaster能够将arrival事件通知当前所有的客户端。
应该翻译成：当每个新的客户端到来时，broadcaster应通知它当前的客户端集合。

**Comment by suntong** [comment]
Agree. will send a PR after my [current one](https://github.com/gopl-zh/gopl-zh.github.com/pull/102) get approved.
