### ISSUE TITLE
一些语句不通顺的地方(估计是笔误)

### ISSUE THREAD

**Issue by VOID001** [golang-china/gopl-zh#6]
- 8.4  Page 228 第一行 "那么channels它们之间的通信机制" might change to "那么channels则是它们之间的通信机制"
- 8.4.4 Page 233  第一行 "向缓存Channel的发送操作就是向内部缓存队列的尾部插入原因" might change to "向缓存Channel的发送操作就是向内部缓存队列的尾部插入元素"

**Comment by cch123** [comment]
已修正
