### ISSUE TITLE
Ch.1.6 Fetching URLs Concurrently: "interleaving" 并发教程的翻译问题

### ISSUE THREAD

**Issue by qzweng** [golang-china/gopl-zh#60]
原文：Having `main` do all the priting ensures that output from each goroutine is processed as a unit, with no danger of interleaving if two goroutines finish at the same time.

翻译：「这个程序中我们用main函数来接收所有fetch函数传回的字符串，可以避免在goroutine异步执行还没有完成时main函数提前退出。」

我认为 "interleaving" 的意思不是 “提前退出”，不是 "leave internally"，而是「交错」的意思。建议翻译为：「使用 main 函数来打印每个 goroutine 的输出，保障了它们能被完整地处理，避免了因为有两个 goroutine 同时完成而使得其输出混淆在一起的危险。」

**Comment by cch123** [comment]
https://github.com/gopl-zh/gopl-zh.github.com，来提 PR 吧~

**Comment by suntong** [comment]
> 建议翻译为：「使用 main 函数来打印每个 goroutine 的输出，保障了它们能被完整地处理，避免了因为有两个 goroutine 同时完成而使得其输出混淆在一起的危险。」

"interleaving" 是「交错」的意思。

建议翻译为：「使用 main 函数来打印每个 goroutine 的输出，保障了它们能被完整地处理，避免了因为有两个 goroutine 同时完成而使得其输出**交错**在一起的危险。」

**Comment by suntong** [comment]
Fixed & Merged.

Can close now.
