### ISSUE TITLE
ch2-01漏翻

### ISSUE THREAD

**Issue by limejuly** [golang-china/gopl-zh#61]
见[此处](https://docs.hacknode.org/gopl-zh/ch2/ch2-01.html )最后一行.
`在习惯上，Go语言程序员推荐使用` 后面没了.

原文为:
`Stylistically, Go programmers use ‘‘camel case’’ when forming names by combining words; that is, interior capital letters are preferred over interior underscores.`

**Comment by cch123** [comment]
https://github.com/gopl-zh/gopl-zh.github.com，来提 PR 吧~
