### ISSUE TITLE
不知道是我理解错了，还是翻译上的错误，自相矛盾

### ISSUE THREAD

**Issue by kirkzhangtech** [golang-china/gopl-zh#73]
![image](https://user-images.githubusercontent.com/46363359/183287285-b0458615-c29b-4c79-b37d-68df51a702b9.png)

**Comment by birdofprey** [comment]
这书有没有更新和pdf版哦。谢谢

**Comment by kirkzhangtech** [comment]
> 这书有没有更新和pdf版哦。谢谢

我用的网页版，不知道有没有pdf

**Comment by chai2010** [comment]
这个翻译没有问题。新的 w 的作用域更靠近内部，因此屏蔽了外部同名变量。最新的网页在 https://gopl-zh.github.io/

可以试试右上角的打印pdf功能
